# -*- coding: utf-8 -*-
"""CPU-only object discovery from Bambu 3MF previews using OpenCV LINEMOD.

The sliced 3MF generated by Bambu Studio already contains a top-view render of
each plate and its per-object XY boxes.  This module turns those renders into
masked shape templates and searches them in a camera frame.  It deliberately
returns observations only: it does not move, pause, or otherwise control a
printer.

OpenCV's LINEMOD implementation is part of opencv_contrib and is released
under OpenCV's Apache-2.0 licence.  The dependency is optional so the rest of
Companion remains usable on a clean macOS installation.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any
import zipfile


class LinemodUnavailable(RuntimeError):
    """Raised when the optional local OpenCV engine is not installed."""


def _opencv() -> tuple[Any, Any]:
    try:
        import cv2  # type: ignore[import-not-found]
        import numpy  # type: ignore[import-not-found]
    except ImportError as exc:
        raise LinemodUnavailable(
            "Moteur Vision OpenCV absent : installe le composant Vision local."
        ) from exc
    if not hasattr(cv2, "linemod"):
        raise LinemodUnavailable("Cette installation OpenCV ne contient pas LINEMOD.")
    return cv2, numpy


def available() -> bool:
    try:
        _opencv()
    except LinemodUnavailable:
        return False
    return True


@dataclass(frozen=True)
class ShapeTemplate:
    object_id: str
    label: str
    image: Any
    mask: Any


@dataclass(frozen=True)
class PlateLayout:
    """A complete rendered plate plus exact per-object masks in its crop."""

    image: Any
    mask: Any
    object_boxes: dict[str, tuple[int, int, int, int]]


def _safe_crop(image: Any, mask: Any, numpy: Any) -> tuple[Any, Any] | None:
    height, width = mask.shape[:2]
    points = numpy.argwhere(mask > 0)
    if not len(points):
        return None
    y0, x0 = points.min(axis=0)
    y1, x1 = points.max(axis=0)
    pad = max(6, round(max(abs(x1 - x0), abs(y1 - y0)) * 0.22))
    x0, y0 = max(0, x0 - pad), max(0, y0 - pad)
    x1, y1 = min(width, x1 + pad + 1), min(height, y1 + pad + 1)
    if x1 - x0 < 12 or y1 - y0 < 12:
        return None
    cropped_mask = mask[y0:y1, x0:x1].copy()
    if int(numpy.count_nonzero(cropped_mask)) < 16:
        return None
    return image[y0:y1, x0:x1].copy(), cropped_mask


def _crop_bounds(mask: Any, numpy: Any) -> tuple[int, int, int, int] | None:
    points = numpy.argwhere(mask > 0)
    if not len(points):
        return None
    y0, x0 = points.min(axis=0)
    y1, x1 = points.max(axis=0)
    pad = max(8, round(max(abs(x1 - x0), abs(y1 - y0)) * 0.06))
    height, width = mask.shape[:2]
    return max(0, int(x0) - pad), max(0, int(y0) - pad), min(width, int(x1) + pad + 1), min(height, int(y1) + pad + 1)


def extract_templates(archive_path: Path, plate_id: str, object_map: dict[str, Any]) -> list[ShapeTemplate]:
    """Extract per-object silhouettes from Bambu's sliced plate preview.

    Bambu's ``pick_<plate>.png`` encodes each canonical skip-object ID in the
    pixel colour.  This makes the 3MF-to-G-code association exact.  A
    detection remains visual evidence only; the canonical object map is still
    the sole source for a manual exclusion.
    """
    cv2, numpy = _opencv()
    top_name = f"Metadata/top_{plate_id}.png"
    pick_name = f"Metadata/pick_{plate_id}.png"
    try:
        with zipfile.ZipFile(archive_path) as archive:
            preview_raw = archive.read(top_name)
            pick_raw = archive.read(pick_name)
    except (KeyError, OSError, zipfile.BadZipFile, json.JSONDecodeError) as exc:
        raise ValueError("Le 3MF ne contient pas l’aperçu de plateau nécessaire à la détection") from exc
    encoded = numpy.frombuffer(preview_raw, dtype=numpy.uint8)
    preview = cv2.imdecode(encoded, cv2.IMREAD_COLOR)
    pick_encoded = numpy.frombuffer(pick_raw, dtype=numpy.uint8)
    pick = cv2.imdecode(pick_encoded, cv2.IMREAD_COLOR)
    if preview is None or pick is None or preview.shape[:2] != pick.shape[:2]:
        raise ValueError("Aperçu de plateau 3MF illisible")
    canonical = {str(item.get("id")): item for item in object_map.get("objects", []) if isinstance(item, dict)
                 and str(item.get("plate") or "") == str(plate_id) and item.get("bounds_xy")}
    templates: list[ShapeTemplate] = []
    for object_id, destination in canonical.items():
        try:
            value = int(object_id)
        except ValueError:
            continue
        colour = numpy.array([[(value >> 16) & 255, (value >> 8) & 255, value & 255]], dtype=numpy.uint8)
        mask = (numpy.all(pick == colour, axis=2).astype(numpy.uint8) * 255)
        crop = _safe_crop(preview, mask, numpy)
        if not crop:
            continue
        image, mask = crop
        templates.append(ShapeTemplate(
            object_id=object_id, label=str(destination.get("label") or "Objet"), image=image, mask=mask,
        ))
    if not templates:
        raise ValueError("Aucune silhouette d’objet n’a pu être construite depuis ce 3MF")
    return templates


def extract_plate_layout(archive_path: Path, plate_id: str, object_map: dict[str, Any]) -> PlateLayout:
    """Build one labelled, full-plate template from Bambu's top/pick previews."""
    cv2, numpy = _opencv()
    top_name = f"Metadata/top_{plate_id}.png"
    pick_name = f"Metadata/pick_{plate_id}.png"
    try:
        with zipfile.ZipFile(archive_path) as archive:
            image = cv2.imdecode(numpy.frombuffer(archive.read(top_name), dtype=numpy.uint8), cv2.IMREAD_COLOR)
            pick = cv2.imdecode(numpy.frombuffer(archive.read(pick_name), dtype=numpy.uint8), cv2.IMREAD_COLOR)
    except (KeyError, OSError, zipfile.BadZipFile) as exc:
        raise ValueError("Le 3MF ne contient pas la vue de dessus nécessaire à la détection") from exc
    if image is None or pick is None or image.shape[:2] != pick.shape[:2]:
        raise ValueError("Vue de dessus 3MF illisible")
    canonical = {str(item.get("id")): item for item in object_map.get("objects", []) if isinstance(item, dict)
                 and str(item.get("plate") or "") == str(plate_id) and item.get("bounds_xy")}
    union = numpy.zeros(pick.shape[:2], dtype=numpy.uint8)
    full_boxes: dict[str, tuple[int, int, int, int]] = {}
    for object_id in canonical:
        try:
            value = int(object_id)
        except ValueError:
            continue
        colour = numpy.array([[(value >> 16) & 255, (value >> 8) & 255, value & 255]], dtype=numpy.uint8)
        object_mask = numpy.all(pick == colour, axis=2).astype(numpy.uint8) * 255
        points = numpy.argwhere(object_mask > 0)
        if not len(points):
            continue
        y0, x0 = points.min(axis=0)
        y1, x1 = points.max(axis=0)
        full_boxes[object_id] = (int(x0), int(y0), int(x1) + 1, int(y1) + 1)
        union = numpy.maximum(union, object_mask)
    crop = _crop_bounds(union, numpy)
    if not crop or not full_boxes:
        raise ValueError("Aucun objet cartographié n’est présent dans le masque 3MF")
    left, top, right, bottom = crop
    boxes = {object_id: (x0 - left, y0 - top, x1 - left, y1 - top)
             for object_id, (x0, y0, x1, y1) in full_boxes.items()}
    return PlateLayout(image=image[top:bottom, left:right].copy(), mask=union[top:bottom, left:right].copy(), object_boxes=boxes)


def _variants(template: ShapeTemplate, cv2: Any, numpy: Any) -> list[tuple[Any, Any]]:
    """Generate constrained perspective views for a camera that moves on the head."""
    image, mask = template.image, template.mask
    height, width = mask.shape[:2]
    corners = numpy.float32([[0, 0], [width - 1, 0], [width - 1, height - 1], [0, height - 1]])
    variants: list[tuple[Any, Any]] = [(image, mask)]
    # LINEMOD is translation tolerant but not fully projective.  These small
    # warps cover the useful shape changes without accepting arbitrary noise.
    for horizontal, vertical in ((0.13, 0.0), (-0.13, 0.0), (0.0, 0.13), (0.0, -0.13)):
        destination = corners.copy()
        destination[0, 0] += horizontal * width
        destination[3, 0] -= horizontal * width
        destination[0, 1] += vertical * height
        destination[1, 1] -= vertical * height
        transform = cv2.getPerspectiveTransform(corners, destination)
        warped_image = cv2.warpPerspective(image, transform, (width, height), borderValue=(0, 0, 0))
        warped_mask = cv2.warpPerspective(mask, transform, (width, height))
        if int(numpy.count_nonzero(warped_mask)) >= 16:
            variants.append((warped_image, warped_mask))
    return variants


def _layout_variants(layout: PlateLayout, cv2: Any, numpy: Any) -> list[tuple[Any, Any, Any]]:
    """Return (image, mask, H) where H maps base layout pixels to a variant."""
    height, width = layout.mask.shape[:2]
    base = numpy.float32([[0, 0], [width - 1, 0], [width - 1, height - 1], [0, height - 1]])
    variants: list[tuple[Any, Any, Any]] = []
    for scale in (0.55, 0.78, 1.0, 1.28):
        scaled_width, scaled_height = max(24, round(width * scale)), max(24, round(height * scale))
        image = cv2.resize(layout.image, (scaled_width, scaled_height), interpolation=cv2.INTER_AREA if scale < 1 else cv2.INTER_CUBIC)
        mask = cv2.resize(layout.mask, (scaled_width, scaled_height), interpolation=cv2.INTER_NEAREST)
        scaled = numpy.float32([[0, 0], [scaled_width - 1, 0], [scaled_width - 1, scaled_height - 1], [0, scaled_height - 1]])
        scale_matrix = numpy.array([[scale, 0, 0], [0, scale, 0], [0, 0, 1]], dtype=numpy.float32)
        for horizontal, vertical in ((0.0, 0.0), (0.14, 0.0), (-0.14, 0.0), (0.0, 0.14), (0.0, -0.14)):
            destination = scaled.copy()
            destination[0, 0] += horizontal * scaled_width
            destination[3, 0] -= horizontal * scaled_width
            destination[0, 1] += vertical * scaled_height
            destination[1, 1] -= vertical * scaled_height
            warp = cv2.getPerspectiveTransform(scaled, destination)
            warped_image = cv2.warpPerspective(image, warp, (scaled_width, scaled_height), borderValue=(0, 0, 0))
            warped_mask = cv2.warpPerspective(mask, warp, (scaled_width, scaled_height))
            if int(numpy.count_nonzero(warped_mask)) >= 32:
                variants.append((warped_image, warped_mask, warp @ scale_matrix))
    return variants


def detect_plate_layout(frame_path: Path, layout: PlateLayout, *, threshold: float = 68.0) -> dict[str, Any]:
    """Locate the complete printed-object layout and recover each object polygon.

    Unlike background registration, the score is derived exclusively from the
    silhouettes rendered from the sliced 3MF.  The caller should hide an
    overlay when ``detected`` is false.
    """
    cv2, numpy = _opencv()
    frame = cv2.imread(str(frame_path), cv2.IMREAD_COLOR)
    if frame is None:
        raise ValueError("Capture Vision illisible")
    detector = cv2.linemod.Detector([cv2.linemod.ColorGradient_create(8, 5, 25)], [8, 4])
    transforms: dict[int, Any] = {}
    for image, mask, transform in _layout_variants(layout, cv2, numpy):
        template_id, _ = detector.addTemplate([image], "plate", mask)
        if template_id >= 0:
            transforms[int(template_id)] = transform
    if not transforms:
        return {"detected": False, "message": "Aucun gabarit 3MF exploitable"}
    matches, _ = detector.match([frame], float(threshold), ["plate"])
    if not matches:
        return {"detected": False, "message": "Aucune forme 3MF reconnue dans cette capture"}
    best = max(matches, key=lambda item: float(item.similarity))
    transform = transforms.get(int(best.template_id))
    if transform is None:
        return {"detected": False, "message": "Transformation du gabarit absente"}
    translation = numpy.array([[1, 0, float(best.x)], [0, 1, float(best.y)], [0, 0, 1]], dtype=numpy.float32)
    transform = translation @ transform
    objects: list[dict[str, Any]] = []
    for object_id, (x0, y0, x1, y1) in layout.object_boxes.items():
        corners = numpy.float32([[[x0, y0], [x1, y0], [x1, y1], [x0, y1]]])
        projected = cv2.perspectiveTransform(corners, transform)[0]
        if not numpy.isfinite(projected).all():
            continue
        objects.append({"object_id": object_id, "points": [[round(float(x), 5), round(float(y), 5)] for x, y in projected]})
    return {
        "detected": bool(objects), "similarity": round(float(best.similarity), 2),
        "objects": objects, "template_id": int(best.template_id),
        "width": int(frame.shape[1]), "height": int(frame.shape[0]),
    }


def detect(frame_path: Path, templates: list[ShapeTemplate], *, threshold: float = 72.0) -> list[dict[str, Any]]:
    """Find rendered 3MF shapes in an RGB capture and return ranked evidence."""
    cv2, numpy = _opencv()
    frame = cv2.imread(str(frame_path), cv2.IMREAD_COLOR)
    if frame is None:
        raise ValueError("Capture Vision illisible")
    detector = cv2.linemod.Detector([cv2.linemod.ColorGradient_create(8, 5, 25)], [8, 4])
    sizes: dict[tuple[str, int], tuple[int, int]] = {}
    labels = {template.object_id: template.label for template in templates}
    for template in templates:
        for image, mask in _variants(template, cv2, numpy):
            template_id, _ = detector.addTemplate([image], template.object_id, mask)
            if template_id >= 0:
                sizes[(template.object_id, int(template_id))] = (int(mask.shape[1]), int(mask.shape[0]))
    matches, _ = detector.match([frame], float(threshold))
    evidence: list[dict[str, Any]] = []
    for match in matches:
        size = sizes.get((str(match.class_id), int(match.template_id)))
        if not size:
            continue
        evidence.append({
            "object_id": str(match.class_id), "label": labels.get(str(match.class_id), "Objet"),
            "x": int(match.x), "y": int(match.y), "width": size[0], "height": size[1],
            "similarity": round(float(match.similarity), 2),
        })
    evidence.sort(key=lambda item: float(item["similarity"]), reverse=True)
    return evidence[:50]
